### PR TITLE
Low power buffer unit testing

### LINKED ISSUE #186: FFD Build error when appconfLOW_POWER_ENABLED=0
```
wanson_inf_eng.c: Error: Undefined reference to 'hold_inf_state'
```

### PR DESCRIPTION
**Pull request by jcarrier-xmos**
This PR also closes #186

### CODE REVIEW

File: examples/ffd/src/app_conf.h [hunk 1]
```diff
@@ -123,12 +123,13 @@
...
- * of "hello" is captured and relayed to the inference engine. */
-#ifndef appconfAUDIO_PIPELINE_BUFFER_NUM_FRAMES
-#define appconfAUDIO_PIPELINE_BUFFER_NUM_FRAMES 32
+/* The number of packets to store in a ring buffer while in low power mode,
+ * where each packet containing appconfAUDIO_PIPELINE_FRAME_ADVANCE frames.
+ * This may be tuned to ensure that unvoiced speech that is a pre-cursor to
+ * voiced speech in a wake-word such as "he" part of "hello" is captured and
+ * relayed to the inference engine. */
+#ifndef appconfAUDIO_PIPELINE_BUFFER_NUM_PACKETS
+#define appconfAUDIO_PIPELINE_BUFFER_NUM_PACKETS 32
```
Comment (jcarrier-xmos) [inline examples/ffd/src/app_conf.h:132]: I am not sure if there is a desired name/term for this, but this variable and other variables in the application were not clearly/correctly named.

File: test/ffd_low_power_audio_buffer/README.md [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+The `build_test.sh` script will copy the test applications and filesystem files
+to the `dist` folder.
+
+## Running Tests
+
+This test runs on `xsim`. Run the test with the following command from the top
+of the repository:
+
+``` console
+bash test/ffd_gpio/run_tests.sh
```
Comment (jcarrier-xmos) [inline test/ffd_low_power_audio_buffer/README.md:29]: I will push a fix to correct this.

File: examples/ffd/src/app_conf.h (hunk 1 above)
Comment (xmos-jmccarthy) [reply examples/ffd/src/app_conf.h:132]: Each audio frame contains 240 samples, or 15ms of audio.

There have been spots where frames and samples were used interchangeably (incorrectly), but in this case, the buffer enqueues 1 frame of 240 samples, so appconfAUDIO_PIPELINE_BUFFER_NUM_FRAMES would be correct.

To prevent confusion, we should fix `frame_count`, for the audio_pipeline_output handlers, as it has not been frame count for a long time.  `frame_count` is samples per frame, so sample_count would be more appropriate.

**Review by xmos-jmccarthy — COMMENTED** [review]
Test built and verified.

File: examples/ffd/src/app_conf.h (hunk 1 above)
Comment (jcarrier-xmos) [reply examples/ffd/src/app_conf.h:132]: I think you are confusing `appconfAUDIO_PIPELINE_BUFFER_NUM_FRAMES` with something else. This is a #define I added with the introduction of this ring buffer. Its only purpose is for sizing the ring buffer.

File: examples/ffd/src/main.c [hunk 3]
```diff
@@ -1,5 +1,5 @@
-// Copyright (c) 2022 XMOS LIMITED. This Software is subject to the terms of the
-// XMOS Public License: Version 1
+// Copyright (c) 2023 XMOS LIMITED.
```
[the remark this answers is not in the document]
Comment (jcarrier-xmos) [reply examples/ffd/src/main.c:1]: Will do, also noticed I missed a couple comments in the test code, which I also address.

File: examples/ffd/src/app_conf.h (hunk 1 above)
Comment (jcarrier-xmos) [reply examples/ffd/src/app_conf.h:132]: Or maybe I am confused by the term frame. I have been thinking of it as equivalent to a sample in the case where there is only one mic.

**Comment by jcarrier-xmos** [comment]
@xmos-jmccarthy, your feedback should have been addressed.

**Review by xmos-jmccarthy — APPROVED** [review]
